trigger:
- master
- release/*

phases:
- phase: Linux
  queue:
    name: Hosted Linux Preview
    matrix:
      Debug:
        _Config: Debug
      Release:
        _Config: Release
  variables:
    DOTNET_HOME: $(Agent.WorkFolder)/.dotnet
  steps:
  - checkout: self
    clean: true
  - script: ./build.sh -ci -p:Configuration=$(_Config)
    displayName: Run build.sh
    timeoutInMinutes: 30
  - script: "ps -ef | awk '$3 ==1{print $0}'"
    condition: always()
    displayName: List orphaned processes
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'artifacts/logs/**/*.trx'