trigger:
- master
- release/*

phases:
- phase: Linux
  queue:
    name: Hosted Linux Preview
  variables:
    DOTNET_HOME: $(Agent.WorkFolder)/.dotnet
  steps:
  - checkout: self
    clean: true
  - script: ./build.sh -ci -bl:artifacts/logs/build.binlog
    displayName: Run build.sh
    timeoutInMinutes: 15
  - script: "ps -ef"
    condition: always()
    displayName: List orphaned processes
  - task: PublishBuildArtifacts@1
    displayName: Upload binlog
    condition: always()
    inputs:
      artifactName: binlog
      artifactType: Container
      pathtoPublish: artifacts/logs/build.binlog
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'artifacts/logs/**/*.trx'
